import { useState } from 'react';
import TopBar from '../components/TopBar';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import bgImage from '../assets/rangeOfMarket.png';
import ibImage from '../assets/img/ib.png';
import './Pages.css';

const BecomeIBPage = () => {
    const [formData, setFormData] = useState({ name: '', email: '', number: '', subject: '', message: '' });
    const [submitted, setSubmitted] = useState(false);

    const handleSubmit = (e) => {
        e.preventDefault();
        setSubmitted(true);
    };

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    return (
        <div className="page-wrapper" style={{ backgroundImage: `url('${bgImage}')`, backgroundAttachment: 'fixed', backgroundSize: 'cover' }}>
            <div className="overlay" style={{ background: 'linear-gradient(to bottom, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.8) 100%)', minHeight: '100vh', width: '100%' }}>
                <TopBar />
                <Navbar />


                <section className="page-section">
                    <div className="container">
                        <div className="section-title">
                            <h2>Become IB</h2>
                            <h3>Partner. Earn. Grow With <span>Galaxy Financial Services</span></h3>
                            <p className="mepsoeo">Become our Introducing Broker (IB) and start earning attractive commissions by referring traders to our platform. Whether you're a trading mentor, community leader, or simply connected within the trading world, our IB partnership lets you monetize your network effortlessly.</p>
                        </div>

                        <div className="row align-items-center mb-5">
                            <div className="col-lg-6 mb-4 mb-lg-0">
                                <div className="content-box h-100">
                                    <h3 className="titleSubTextspan" style={{ color: '#00bac7', marginBottom: '20px' }}>What is an IB?</h3>
                                    <p>An Introducing Broker (IB) connects new clients to our platform. You earn a share of revenue generated by your referrals without managing trades or handling funds.</p>
                                    <ul style={{ listStyle: 'none', paddingLeft: 0, color: '#ddd' }}>
                                        <li className="mb-2">- Earn attractive, recurring commissions</li>
                                        <li className="mb-2">- Access professional marketing materials</li>
                                        <li className="mb-2">- Track your referrals in real-time</li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <img src={ibImage} className="img-fluid rounded shadow" alt="IB Partnership" style={{ maxHeight: '320px', objectFit: 'contain' }} />
                            </div>
                        </div>

                        <div className="mb-5">
                            <div className="section-title text-start mb-4">
                                <h3 className="mb-0">How It <span>Works</span></h3>
                            </div>
                            <div className="row g-4">
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="step-card content-box p-4 h-100">
                                        <div className="icon-circle mb-4" style={{ margin: '0' }}>👤</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.25rem', fontWeight: '700' }}>1. Register</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Sign up and get your unique referral link to start your journey.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="step-card content-box p-4 h-100">
                                        <div className="icon-circle mb-4" style={{ margin: '0' }}>↗</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.25rem', fontWeight: '700' }}>2. Refer</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Share your link with your community, friends, or clients.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="step-card content-box p-4 h-100">
                                        <div className="icon-circle mb-4" style={{ margin: '0' }}>💰</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.25rem', fontWeight: '700' }}>3. Earn</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Receive attractive commissions on every active referral.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="step-card content-box p-4 h-100">
                                        <div className="icon-circle mb-4" style={{ margin: '0' }}>📈</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.25rem', fontWeight: '700' }}>4. Grow</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Build your sub-IB network and maximize your long-term earnings.</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="mb-5">
                            <div className="section-title text-start mb-4">
                                <h3 className="mb-0">Partner <span>Benefits</span></h3>
                            </div>
                            <div className="row g-4">
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="content-box p-4 h-100">
                                        <div className="mb-3" style={{ fontSize: '2rem', color: '#FFC107' }}>💵</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.15rem', fontWeight: '700' }}>High Commissions</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Earn competitive payouts and bonuses on every active referral.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="content-box p-4 h-100">
                                        <div className="mb-3" style={{ fontSize: '2rem', color: '#FFC107' }}>📊</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.15rem', fontWeight: '700' }}>IB Dashboard</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Track your clients, trading activity, and rewards in real-time.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="content-box p-4 h-100">
                                        <div className="mb-3" style={{ fontSize: '2rem', color: '#FFC107' }}>🎧</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.15rem', fontWeight: '700' }}>Dedicated Support</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Access 24/7 partner support and professional marketing assistance.</p>
                                    </div>
                                </div>
                                <div className="col-lg-3 col-md-6 col-12">
                                    <div className="content-box p-4 h-100">
                                        <div className="mb-3" style={{ fontSize: '2rem', color: '#FFC107' }}>✅</div>
                                        <h4 className="text-white mb-2" style={{ fontSize: '1.15rem', fontWeight: '700' }}>On-Time Payments</h4>
                                        <p className="small mb-0 text-muted" style={{ lineHeight: '1.6' }}>Receive your commissions through multiple methods, on time, every time.</p>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div className="content-box mb-5">
                            <h3 className="titleSubTextspan mb-4" style={{ color: '#00bac7' }}>Commission Models</h3>
                            <div className="table-responsive">
                                <table className="c_table table-bordered text-center">
                                    <thead>
                                        <tr>
                                            <th className="bgHeadColor">Model</th>
                                            <th className="bgHeadColor">Description</th>
                                            <th className="bgHeadColor">Example Rate</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr><td>Revenue Share</td><td>Percentage of revenue generated by referrals</td><td>10% – 30%</td></tr>
                                        <tr><td>Tiered</td><td>Higher payouts for higher referral volume</td><td>Up to 35%</td></tr>
                                        <tr><td>CPA / Hybrid</td><td>Fixed CPA + revenue share combo</td><td>$50 + 5%</td></tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div className="content-box">
                            <div className="section-title">
                                <h3 style={{ color: '#fff' }}>Ready to Partner?</h3>
                                <p className="mepsoeo">Fill out the form below to apply for our IB Program. Our team will review your application within 24–48 hours.</p>
                            </div>
                            <form onSubmit={handleSubmit} className="php-email-form">
                                <div className="row g-3">
                                    <div className="col-md-6">
                                        <input type="text" name="name" className="form-control form-control-calc" placeholder="Your Name" value={formData.name} onChange={handleChange} required />
                                    </div>
                                    <div className="col-md-6">
                                        <input type="email" name="email" className="form-control form-control-calc" placeholder="Your Email" value={formData.email} onChange={handleChange} required />
                                    </div>
                                    <div className="col-md-6">
                                        <input type="tel" name="number" className="form-control form-control-calc" placeholder="Your Number" value={formData.number} onChange={handleChange} required />
                                    </div>
                                    <div className="col-md-6">
                                        <input type="text" name="subject" className="form-control form-control-calc" placeholder="Your Subject" value={formData.subject} onChange={handleChange} required />
                                    </div>
                                    <div className="col-12">
                                        <textarea name="message" className="form-control form-control-calc" placeholder="Message" rows="4" value={formData.message} onChange={handleChange}></textarea>
                                    </div>
                                    <div className="col-12 text-center">
                                        <button type="submit" className="btn btn-calc-submit">Send Message</button>
                                    </div>
                                </div>
                                {submitted && <p className="text-success text-center mt-3 mb-0">Your message has been sent. Thank you!</p>}
                            </form>
                        </div>

                        <div className="content-box mt-5">
                            <h6 style={{ color: '#FFC107' }}>Disclaimers:</h6>
                            <p>Galaxy Financial Services Ltd does not provide or facilitate business services or transactions to residents of the USA, UAE, North Korea, IRAN, MYANMAR or any other country that may be subject to any international sanctions.</p>
                            <h6 style={{ color: '#FFC107', marginTop: '15px' }}>Risk Warning:</h6>
                            <p>The financial products offered via this website include digitals, contracts for difference (CFDs), and other complex derivatives and financial products. Trading options may not be suitable for everyone. Trading CFDs carries a high level of risk since leverage can work both to your advantage and disadvantage. As a result, the products offered on this website may not be suitable for all investors because of the risk of losing all of your invested capital. You should never invest money that you cannot afford to lose, and never trade with borrowed money. Before trading in the complex financial products offered, please be sure to understand the risks involved and learn about Secure and responsible trading.</p>
                            <p>Forex and CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 70% of retail investor accounts lose money when forex and CFDs trading with this provider. You should consider whether you can afford to take the high risk of losing your money.</p>
                        </div>
                    </div>
                </section>

                <Footer />
            </div>
        </div>
    );
};

export default BecomeIBPage;
